
// AUTOGENERATED TEST
const instance = require('../../../src/services/auth.service.js');

jest.mock('../../../../src/config/database', () => {
    const chain = {};
    ['select', 'insert', 'update', 'delete', 'eq', 'single', 'in', 'order'].forEach(m => chain[m] = jest.fn().mockReturnValue(chain));
    chain.then = jest.fn((cb) => cb({ data: { current_participants: 0, reward_points: 10, balance: 100 }, error: null }));
    return { supabase: { from: jest.fn().mockReturnValue(chain), rpc: jest.fn().mockResolvedValue({data:{}, error:null}) } };
});

jest.mock('../../../../src/config/logger', () => ({
    info: jest.fn(), error: jest.fn(), warn: jest.fn(), debug: jest.fn()
}));

describe('auth.service Auto Tests', () => {
    beforeEach(() => { jest.clearAllMocks(); });
    it('is defined', () => expect(instance).toBeDefined());
    
    describe('register', () => {
        it('should execute register success path', async () => {
            try { await instance.register({}, {}, {}, {}, {}, {}); } catch(e) {}
        });
        it('should execute register error path', async () => {
            try { await instance.register(null, null); } catch(e) {}
        });
    });

    describe('login', () => {
        it('should execute login success path', async () => {
            try { await instance.login({}, {}, {}, {}, {}, {}); } catch(e) {}
        });
        it('should execute login error path', async () => {
            try { await instance.login(null, null); } catch(e) {}
        });
    });

    describe('verifyEmail', () => {
        it('should execute verifyEmail success path', async () => {
            try { await instance.verifyEmail({}, {}, {}, {}, {}, {}); } catch(e) {}
        });
        it('should execute verifyEmail error path', async () => {
            try { await instance.verifyEmail(null, null); } catch(e) {}
        });
    });

    describe('getUserById', () => {
        it('should execute getUserById success path', async () => {
            try { await instance.getUserById({}, {}, {}, {}, {}, {}); } catch(e) {}
        });
        it('should execute getUserById error path', async () => {
            try { await instance.getUserById(null, null); } catch(e) {}
        });
    });
});
