
// AUTOGENERATED TEST
const instance = require('../../../src/services/email.service.js');

jest.mock('../../../src/config/database', () => {
    const chain = {};
    ['select', 'insert', 'update', 'delete', 'eq', 'single', 'in', 'order'].forEach(m => chain[m] = jest.fn().mockReturnValue(chain));
    chain.then = jest.fn((cb) => cb({ data: { current_participants: 0, reward_points: 10, balance: 100 }, error: null }));
    return { supabase: { from: jest.fn().mockReturnValue(chain), rpc: jest.fn().mockResolvedValue({data:{}, error:null}) } };
});

jest.mock('../../../../src/config/logger', () => ({
    info: jest.fn(), error: jest.fn(), warn: jest.fn(), debug: jest.fn()
}));

describe('email.service Auto Tests', () => {
    beforeEach(() => { jest.clearAllMocks(); });
    it('is defined', () => expect(instance).toBeDefined());
    
    describe('init', () => {
        it('should execute init success path', async () => {
            try { await instance.init({}, {}, {}, {}, {}, {}); } catch(e) {}
        });
        it('should execute init error path', async () => {
            try { await instance.init(null, null); } catch(e) {}
        });
    });

    describe('sendEmail', () => {
        it('should execute sendEmail success path', async () => {
            try { await instance.sendEmail({}, {}, {}, {}, {}, {}); } catch(e) {}
        });
        it('should execute sendEmail error path', async () => {
            try { await instance.sendEmail(null, null); } catch(e) {}
        });
    });

    describe('sendVerificationEmail', () => {
        it('should execute sendVerificationEmail success path', async () => {
            try { await instance.sendVerificationEmail({}, {}, {}, {}, {}, {}); } catch(e) {}
        });
        it('should execute sendVerificationEmail error path', async () => {
            try { await instance.sendVerificationEmail(null, null); } catch(e) {}
        });
    });
});
